version: '3.9'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  web:
    build: .
    volumes:
      - .:/var/app/project
    command: sh -c 'npm i && npm start'
    depends_on:
      - redis